### ISSUE TITLE
Backlog(Frontend)

### ISSUE THREAD

**Issue by FabricaAdso** [FabricaAdso/lisa-front#22]
# Frontend
## Diseño
* [ ] FabricaAdso/lisa-front#3
* [x] FabricaAdso/lisa-front#11
## Gestión de privilegios
* [x] FabricaAdso/lisa-front#1
* [x] FabricaAdso/lisa-front#2
* [x] FabricaAdso/lisa-front#8
* [ ] FabricaAdso/lisa-front#15
### Definir roles a usuarios por parte centro de formación
* [ ] FabricaAdso/lisa-front#21
## Admin(pausa)
* [x] FabricaAdso/lisa-front#4
* [x] FabricaAdso/lisa-front#5
## Gestión de asistencias
* [ ] FabricaAdso/lisa-front#9
* [ ] FabricaAdso/lisa-front#12 
* [ ] FabricaAdso/lisa-front#13
* [ ] FabricaAdso/lisa-front#14
* [ ] FabricaAdso/lisa-front#16
* [ ] FabricaAdso/lisa-front#29
## Otras tareas
* [x] FabricaAdso/lisa-front#10
